source 'https://rubygems.org'

gem 'knife-solo', '~> 0.4'
gem 'knife-solo_data_bag'
gem 'chef', '~> 11.8'
gem 'berkshelf'
gem 'test-kitchen', '~> 1.0.0.beta.4', group: :integration
gem 'kitchen-bluebox'
